// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN3y-3oLe5CYJxyP7e32viVeH_8Zvj5mA',
    appId: '1:681970363918:web:0532927f95f65a3bb2965f',
    messagingSenderId: '681970363918',
    projectId: 'trongtre-first-project-flutter',
    authDomain: 'trongtre-first-project-flutter.firebaseapp.com',
    storageBucket: 'trongtre-first-project-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr85badvIcymuEFhYn3qRhnWSK34c2C9Q',
    appId: '1:681970363918:android:59c659244c8e7f2cb2965f',
    messagingSenderId: '681970363918',
    projectId: 'trongtre-first-project-flutter',
    storageBucket: 'trongtre-first-project-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrd09Zin57e2ol6daDt17KUYuMeqVReD0',
    appId: '1:681970363918:ios:e5e29a939dfb7b6bb2965f',
    messagingSenderId: '681970363918',
    projectId: 'trongtre-first-project-flutter',
    storageBucket: 'trongtre-first-project-flutter.appspot.com',
    iosClientId: '681970363918-kapcho65lijqht6r6ps3qvur2hdqbppc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrd09Zin57e2ol6daDt17KUYuMeqVReD0',
    appId: '1:681970363918:ios:17caf55bd35e1d79b2965f',
    messagingSenderId: '681970363918',
    projectId: 'trongtre-first-project-flutter',
    storageBucket: 'trongtre-first-project-flutter.appspot.com',
    iosClientId: '681970363918-3qht0o28vqjtn2glq65f5ns4bcd1i7fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTutorial.RunnerTests',
  );
}
